### PR TITLE
Write unicode to the file so it complains less.  Fixes #97

### LINKED ISSUE #97: TypeError: must be unicode, not str
```
bash-3.2$ git clone gitifyhg::ssh://hg@bitbucket.org/phoebian/inquisitor
Cloning into 'inquisitor'...
Checking connectivity... done.
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-gitifyhg", line 9, in <module>
    load_entry_point('gitifyhg==0.8.4', 'console_scripts', 'git-remote-gitifyhg')()
  File "/Library/Python/2.7/site-packages/gitifyhg/gitifyhg.py", line 344, in main
    HGRemote(*[x.decode('utf-8') for x in args]).process()
  File "/Library/Python/2.7/site-packages/gitifyhg/gitifyhg.py", line 207, in process
    self.marks.store()
  File "/Library/Python/2.7/site-packages/gitifyhg/util.py", line 209, in store
    file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
TypeError: must be unicode, not str
```

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by andreif** [comment]
:+1: 

Although, I would remove the profanity instead of fixing grammar mistakes in it...

**Comment by fingolfin** [comment]
I'd tend to agree with andreif... But more to the point, I am afraid this project is mostly dead / inactive right now. So for now I myself switched back to a patched version of Felipe's git-remote-hg (which he seems to have abandonend, at least for the time being, so I made a fork of it: https://github.com/fingolfin/git-remote-hg/)

**Comment by asottile** [comment]
Yeah I noticed the same thing after posting the PR.  sadness!

**Comment by buchuki** [comment]
It's true that this has become abandonware; my current company's repos are so big that this gateway simply doesn't work for me. However, I'm happy to give it up for adoption if anyone wants to use it. git-remote-hg and gitifyhg both have bugs that the other doesn't have, so it would be great if one of them were to become a clear winner.

**Pull request merged**
